### ISSUE TITLE
Feature request: Ability to blacklist a world

### ISSUE THREAD

**Issue by jordi00113** [Blautee/AutoReplant#2]
Add the ability to block certain worlds where this feature should be disabled

''
As an administrator
I want to exclude certain worlds
so minecraft players cannot use this functionality on certain worlds
''

**Comment by Blautee** [comment]
good idea, will work on that!

**Comment by jordi00113** [comment]
In my opinion, set by config list + command in game

I'm happy to test your code & plugin

**Comment by Blautee** [comment]
both added, thanks!
