### ISSUE TITLE
[Feature Request] add to compatibility to superior skyblock 2

### ISSUE THREAD

**Issue by KaBoom13** [Blautee/AutoReplant#3]
adding a property that will make it so that if someone is not devoted to the island, they cannot use the hoe on the crops from the island

**Comment by Blautee** [comment]
i see the issue. protections seem to be ignored. but since your skyblock scenario is very special, i will think about some kind of worldguard integration. i guess worldguard is most common and is probably also supported by your skyblock plugin.

**Comment by Blautee** [comment]
worldguard support is added. i hope that works for you, thanks for the idea!
